FILES = ProducerConsumer.java Producer.java Consumer.java CircularBuffer.java
all:
	javac -d . $(FILES)
run:
	java HW4.ProducerConsumer
clean:
	rm ./HW4/*.class
package:
	zip -r Seefeldt-Tyler-HW4.zip $(Files) Makefile README.txt