FILES = ProducerConsumer.java Producer.java Consumer.java CircularBuffer.java
all:
	javac -d . $(FILES)
run:
	java ProducerConsumer
clean:
	rm *.class
package:
	zip -r Seefeldt-Tyler-HW4.zip ProducerConsumer.java Producer.java Consumer.java CircularBuffer.java Makefile README.txt